# .github/workflows/youtube_analysis.yml
name: YouTube Kids Channel Analysis

on:
  # Manual trigger from GitHub
  workflow_dispatch:
    inputs:
      run_description:
        description: 'Description of this analysis run'
        required: false
        default: 'Manual analysis run'
  
  # Scheduled runs (optional - runs every Monday at 9 AM UTC)
  schedule:
    - cron: '0 9 * * 1'
  
  # Trigger via repository dispatch (for Google Sheets integration)
  repository_dispatch:
    types: [run-youtube-analysis]

jobs:
  analyze-youtube-channels:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run YouTube analysis
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
      run: |
        python main.py
    
    - name: Upload results as artifact
      uses: actions/upload-artifact@v3
      with:
        name: youtube-analysis-results
        path: results.json
        retention-days: 30
